### PR TITLE
MessageManager Support

### PR DESCRIPTION
**Pull request by ppetrosh**

### CODE REVIEW

**Comment by mm-gmbd** [comment]
Hey Pavel -- I branched off of this branch and am trying to open a PR with some changes now, but GH is saying that I don't have permissions to do so :/ let me figure out this auth issue and you should have my changes soon!

**Comment by mm-gmbd** [comment]
Still having auth issues... any chance there are some auth settings on this repo that aren't set to allow PRs from non-organization members?

**Comment by ppetrosh** [comment]
That's strange. No specific settings for the repository. Let me double check.

**Comment by mm-gmbd** [comment]
Hey @ppetrosh -- I think I know why... I didn't fork the repository, I just cloned from GH. I'll fork and retry.

**Comment by ppetrosh** [comment]
Yes, sure. You need to fork it first.

**Comment by mm-gmbd** [comment]
Okay, opened another PR as it wouldn't let me open a PR on a PR (apparently that's not an allowed action). PR #7 is where I've got my commit.

**Comment by ppetrosh** [comment]
Thank you @mm-gmbd for taking care of the changes. I merged the PR with just minor modifications.

**Comment by betzrhodes** [comment]
Closing this pull request without merging. impPager is shifting to ReplayMessenger - no support for MessageManager planned.

**Pull request closed without merging**
