### PR TITLE
The new RM implementation

### PR DESCRIPTION
**Pull request by ragrus-nbl**
The new RM:
1) Is fully independent from MessageManager.
2) Uses SPIFlashLogger and ConnectionManager.
3) Consists of two parts (classes): base and extended (inherited from the base part).
4) Every message has "importance" parameter which will be specified by user in the send() method. "Importance" can be: 0, 1 and 2.
5) If importance = 0, the message will not be persisted and will not be resent in case of failure. Just one try and the onFail() will be called.
6) If importance = 1, the message will be automatically persisted in case of failure (with no call of the onFail()). Then it will be "replayed" once connection is reestablished.
7) If importance = 2, the message will be instantly persisted. In case of failure it will be "replayed" once connection is reestablished.
8) The base part supports only importance = 0 and is intended to be used on imp agent.
9) The extended version supports all values of importance and is intended to be used on imp device when persistence is needed.
10) No local (message-specific) callbacks. Because all local callbacks will be lost once message is persisted (a function cannot be saved to flash) or device rebooted. The main point of local callbacks is the ability of usage of local context. But if user has to re-set their callbacks (on "replaying" messages from storage or reboot), they will have their context already been lost.
11) There are 3 global callbacks for outbound messages: onAck(), onFail(), confirmResend() (available only in the extended part).
12) For inbound messages there are on() and defaultOn() callbacks.
13) confirmResend() callback is called during the "replaying" process - when the connection has been reestablished and the lib suggests to user to resend some (or all) of pending messages persisted on the flash. This callback is called for every message from the flash so that user is able to "evaluate" it and send/not send. confirmResend() user callback must return bool value: true to resend the message and false otherwise.
14) If confirmResend() returns false, the onFail() callback is called for the message.
15) If the lib has to delete some message from flash memory (memory is full), the onFail() callback is called for that message.
16) Instead of replies, customized acknowledges (customAck's) are allowed.
17) An opportunity to manage acks is given to applications. An application will be able to: send an empty ack, send an ack with some data, not send any ack.
18) An ack can be sent synchronously and asynchronously as well.
19) customAck is a kind of non-guaranteed reply which is assumed to be sent within the specified timeout. The sender side decides the sending fails (and may resend the same msg) if no ack is received within that timeout.
IMG_20190305_145145

### CODE REVIEW

**Comment by ragrus-nbl** [comment]
We should think about how to better name the classes. For example, Extended is not used on the agent side, while the Base can/should be used on both: agent and device sides. Something to think about in the future

**Comment by betzrhodes** [comment]
Thanks. I will try to take a look at this in the next couple days.

**Comment by betzrhodes** [comment]
Merging to develop, where I can clean up docs and prep for release.

**Comment by ppetrosh** [comment]
@betzrhodes just to clarify. Do you have no concerns/questions about the code?

**Comment by terrencebarr** [comment]
Didn't look at the code in detail, but the high-level description makes sense. Let's give Betsy a chance to review it.

**Comment by betzrhodes** [comment]
@ppetrosh @ragrus-nbl 

I've skimmed through the code and the summery, and it looks to be in sync. The questions I have are higher level.
 
- The naming bothers me
   - The base class as written is just a simple messenger class - there are no retries or ability to set the priority. Therefore it seems wrong to name this library ReplayMessenger. For lack of a better name Messenger seems more appropriate, if there are no plans to add any of the priority/retry features to this base class (see Features comment below). 
  - The extension adds Persistence and Retries. Here is were it makes sense to call the library ReplayMessenger. 

- Features, I really like the streamlined messaging design. The one area I keep circling back to is the lack of support for the "replay" features if no SPI flash is involved. I think the priority and retry logic could be useful on both agent and device even if they are just creating locally stored messaging queues. I'd really like to get as much leverage out of this messaging design as possible, and if we separate the persist logic from the priority and retry logic it would open the library up to more applications. To be clear this is just a thought at this point, and not anything we should put extra effort into at the moment. I only bring it up since it might change the way we name things now. 

I'm currently working on the detailed API docs and confirming my understanding of the library features as I go. I'm looking to publish sometime this week/early next week with naming changes based on this thread.

**Comment by ppetrosh** [comment]
Thank you @betzrhodes !

**Comment by betzrhodes** [comment]
Opened new pull request #9  - docs roughed in, classes re-named, added _typeof function to message class.

**Pull request merged**
